# Generated by Django 2.2.14 on 2020-07-21 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('editorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='created_at',
            field=models.DateTimeField(auto_created=django.utils.timezone.now, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
