# Generated by Django 2.2.14 on 2020-07-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorials', '0002_editorial_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
